# Generated by Django 5.0.3 on 2024-03-24 20:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('current_price', models.IntegerField()),
                ('photo', models.CharField(max_length=256)),
                ('category', models.IntegerField(choices=[(None, 'uncategorized'), (0, 'Fashion'), (1, 'Toys'), (2, 'Home & Garden'), (3, 'Music'), (4, 'Books & Magazines'), (5, 'Computers/Tablets'), (6, 'Video Games & Consoles')])),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('response', models.TextField(null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_price', models.IntegerField()),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.auction')),
            ],
        ),
    ]
