# Generated by Django 5.0.3 on 2024-03-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='creator_user',
            new_name='seller_user',
        ),
    ]
