# Generated by Django 5.0.3 on 2024-04-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_bid_creator_user_remove_comment_creator_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='response',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
