# Generated by Django 5.0.3 on 2024-04-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment_update_date_alter_comment_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=512),
        ),
    ]
