# Generated by Django 5.0.3 on 2024-04-07 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_comment_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auction_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='auction_id',
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='auction_bids', to='auctions.auction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='auction',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='auction_comments', to='auctions.auction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
