# Generated by Django 5.0.3 on 2024-04-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_bid_auction_id_remove_comment_auction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='auction',
            name='photo',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
