# Generated by Django 5.0.3 on 2024-05-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auction_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='is_active',
            new_name='is_closed',
        ),
    ]
