# Generated by Django 5.0.3 on 2024-05-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_rename_is_active_auction_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
